"""Type stubs for the mammocat Rust extension module."""

from pathlib import Path
from typing import Any, Literal

__version__: str
BREAST_TOMOSYNTHESIS_SOP_CLASS_UID: str

# Exceptions
class MammocatError(Exception):
    """Base exception for all mammocat errors."""

class DicomError(MammocatError):
    """DICOM reading or parsing error."""

class TagNotFoundError(MammocatError):
    """Required DICOM tag not found in file."""

class InvalidValueError(MammocatError):
    """Invalid DICOM tag value encountered."""

class ExtractionError(MammocatError):
    """Generic metadata extraction error."""

class SelectionError(MammocatError):
    """Preferred-view selection error."""

# Enums
class MammogramType:
    """Mammogram type classification."""

    UNKNOWN: MammogramType
    TOMO: MammogramType
    FFDM: MammogramType
    SYNTH: MammogramType
    SFM: MammogramType

    @property
    def value(self) -> str: ...
    def is_unknown(self) -> bool: ...
    def simple_name(self) -> str: ...
    def is_preferred_to(self, other: MammogramType) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __lt__(self, other: MammogramType) -> bool: ...
    def __le__(self, other: MammogramType) -> bool: ...
    def __gt__(self, other: MammogramType) -> bool: ...
    def __ge__(self, other: MammogramType) -> bool: ...

class DbtObjectKind:
    """DBT object storage representation."""

    NONE: DbtObjectKind
    VOLUME: DbtObjectKind
    SLICE: DbtObjectKind
    UNKNOWN: DbtObjectKind

    @property
    def value(self) -> str: ...
    def simple_name(self) -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Laterality:
    """Laterality specification (left/right/bilateral)."""

    UNKNOWN: Laterality
    NONE: Laterality
    LEFT: Laterality
    RIGHT: Laterality
    BILATERAL: Laterality

    @property
    def value(self) -> str: ...
    def is_unknown(self) -> bool: ...
    def is_unilateral(self) -> bool: ...
    def is_unknown_or_none(self) -> bool: ...
    def opposite(self) -> Laterality: ...
    def short_str(self) -> str: ...
    def simple_name(self) -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ViewPosition:
    """View position enumeration."""

    UNKNOWN: ViewPosition
    XCCL: ViewPosition
    XCCM: ViewPosition
    CC: ViewPosition
    MLO: ViewPosition
    ML: ViewPosition
    LMO: ViewPosition
    LM: ViewPosition
    AT: ViewPosition
    CV: ViewPosition

    @property
    def value(self) -> str: ...
    def is_unknown(self) -> bool: ...
    def is_standard_view(self) -> bool: ...
    def is_mlo_like(self) -> bool: ...
    def is_cc_like(self) -> bool: ...
    def short_str(self) -> str: ...
    def simple_name(self) -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __lt__(self, other: ViewPosition) -> bool: ...
    def __le__(self, other: ViewPosition) -> bool: ...
    def __gt__(self, other: ViewPosition) -> bool: ...
    def __ge__(self, other: ViewPosition) -> bool: ...

class PreferenceOrder:
    """Preference ordering strategy for selecting preferred mammogram types."""

    DEFAULT: PreferenceOrder
    TOMO_FIRST: PreferenceOrder

    @property
    def value(self) -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class PhotometricInterpretation:
    """Photometric interpretation enumeration."""

    UNKNOWN: PhotometricInterpretation
    MONOCHROME1: PhotometricInterpretation
    MONOCHROME2: PhotometricInterpretation
    PALETTE_COLOR: PhotometricInterpretation
    RGB: PhotometricInterpretation
    HSV: PhotometricInterpretation
    ARGB: PhotometricInterpretation
    CMYK: PhotometricInterpretation
    YBR_FULL: PhotometricInterpretation
    YBR_FULL_422: PhotometricInterpretation
    YBR_PARTIAL_422: PhotometricInterpretation
    YBR_PARTIAL_420: PhotometricInterpretation
    YBR_ICT: PhotometricInterpretation
    YBR_RCT: PhotometricInterpretation

    @property
    def value(self) -> str: ...
    def is_monochrome(self) -> bool: ...
    def is_inverted(self) -> bool: ...
    def num_channels(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

# Data structures
class ImageType:
    """DICOM ImageType field decomposed into components."""
    def __init__(
        self,
        pixels: str,
        exam: str,
        flavor: str | None = None,
        extras: list[str] | None = None,
    ) -> None: ...
    @property
    def pixels(self) -> str: ...
    @property
    def exam(self) -> str: ...
    @property
    def flavor(self) -> str | None: ...
    @property
    def extras(self) -> list[str] | None: ...
    def contains(self, value: str) -> bool: ...
    def is_valid(self) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class MammogramView:
    """Mammogram view combining laterality and view position."""
    def __init__(self, laterality: Laterality, view: ViewPosition) -> None: ...
    @property
    def laterality(self) -> Laterality: ...
    @property
    def view(self) -> ViewPosition: ...
    def is_standard_mammo_view(self) -> bool: ...
    def is_mlo_like(self) -> bool: ...
    def is_cc_like(self) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class MammogramMetadata:
    """Extracted mammography metadata."""
    @property
    def mammogram_type(self) -> MammogramType: ...
    @property
    def dbt_object_kind(self) -> DbtObjectKind: ...
    @property
    def laterality(self) -> Laterality: ...
    @property
    def view_position(self) -> ViewPosition: ...
    @property
    def image_type(self) -> ImageType: ...
    @property
    def is_for_processing(self) -> bool: ...
    @property
    def has_implant(self) -> bool: ...
    @property
    def is_spot_compression(self) -> bool: ...
    @property
    def is_magnified(self) -> bool: ...
    @property
    def is_implant_displaced(self) -> bool: ...
    @property
    def manufacturer(self) -> str | None: ...
    @property
    def model(self) -> str | None: ...
    @property
    def number_of_frames(self) -> int: ...
    @property
    def concatenation_uid(self) -> str | None: ...
    @property
    def sop_instance_uid_of_concatenation_source(self) -> str | None: ...
    @property
    def is_secondary_capture(self) -> bool: ...
    @property
    def modality(self) -> str | None: ...
    @property
    def transfer_syntax_uid(self) -> str | None: ...
    @property
    def transfer_syntax_name(self) -> str | None: ...
    @property
    def compression_type(self) -> str | None: ...
    def mammogram_view(self) -> MammogramView: ...
    def is_standard_view(self) -> bool: ...
    def is_2d(self) -> bool: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class MammogramRecord:
    """Mammogram record combining file path and extracted metadata."""
    @staticmethod
    def from_file(path: str | Path) -> MammogramRecord: ...
    @staticmethod
    def from_bytes(data: bytes, id: str | None = None) -> MammogramRecord: ...
    @property
    def file_path(self) -> str: ...
    @property
    def metadata(self) -> MammogramMetadata: ...
    @property
    def study_instance_uid(self) -> str | None: ...
    @property
    def series_instance_uid(self) -> str | None: ...
    @property
    def sop_instance_uid(self) -> str | None: ...
    @property
    def rows(self) -> int | None: ...
    @property
    def columns(self) -> int | None: ...
    @property
    def transfer_syntax_uid(self) -> str | None: ...
    @property
    def is_lossy_compressed(self) -> bool: ...
    @property
    def is_implant_displaced(self) -> bool: ...
    @property
    def is_spot_compression(self) -> bool: ...
    @property
    def is_magnified(self) -> bool: ...
    def image_area(self) -> int | None: ...
    def is_spot_or_mag(self) -> bool: ...
    def is_preferred_to(self, other: MammogramRecord) -> bool: ...
    def is_preferred_to_with_order(
        self, other: MammogramRecord, preference_order: PreferenceOrder
    ) -> bool: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

# Main API
class MammogramExtractor:
    """Main extractor for mammography metadata from DICOM files."""
    @staticmethod
    def extract_from_file(path: str | Path) -> MammogramMetadata: ...
    @staticmethod
    def extract_from_file_with_options(
        path: str | Path, is_sfm: bool = False
    ) -> MammogramMetadata: ...

def validate_dicom(
    path: str | Path,
    profile: Literal["selection", "extraction"] = "selection",
) -> dict[str, Any]:
    """Validate one DICOM file for mammocat extraction or mammoselect readiness."""

def validate_directory(
    path: str | Path,
    profile: Literal["selection", "extraction"] = "selection",
    filter_config: FilterConfig | None = None,
    preference_order: PreferenceOrder | None = None,
) -> dict[str, Any]:
    """Validate a DICOM directory or ZIP archive and report preferred-view coverage."""

# Filter configuration
class FilterConfig:
    """Configuration for filtering mammogram records during selection."""
    def __init__(
        self,
        allowed_types: list[MammogramType] | None = None,
        exclude_implants: bool = False,
        exclude_non_standard_views: bool = False,
        exclude_for_processing: bool = True,
        exclude_secondary_capture: bool = True,
        exclude_non_mg_modality: bool = True,
        require_common_modality: bool = False,
        exclude_lossy_compressed: bool = False,
        deprioritize_lossy_compressed: bool = True,
        allowed_dbt_object_kinds: list[DbtObjectKind] | None = None,
    ) -> None: ...
    @staticmethod
    def default() -> FilterConfig: ...
    @staticmethod
    def permissive() -> FilterConfig: ...
    @property
    def allowed_types(self) -> list[MammogramType] | None: ...
    @property
    def allowed_dbt_object_kinds(self) -> list[DbtObjectKind] | None: ...
    @property
    def exclude_implants(self) -> bool: ...
    @property
    def exclude_non_standard_views(self) -> bool: ...
    @property
    def exclude_for_processing(self) -> bool: ...
    @property
    def exclude_secondary_capture(self) -> bool: ...
    @property
    def exclude_non_mg_modality(self) -> bool: ...
    @property
    def require_common_modality(self) -> bool: ...
    @property
    def exclude_lossy_compressed(self) -> bool: ...
    @property
    def deprioritize_lossy_compressed(self) -> bool: ...
    def __repr__(self) -> str: ...

# Selection functions
def get_preferred_views(
    records: list[MammogramRecord],
    strict: bool = False,
) -> dict[MammogramView, MammogramRecord | None]:
    """Select preferred views from records using default preference order.

    For each of the 4 standard views (L-MLO, R-MLO, L-CC, R-CC), selects the
    most preferred mammogram based on comparison logic using the default
    preference order (FFDM > SYNTH > TOMO > SFM).

    Args:
        records: List of MammogramRecord objects to select from
        strict: If False, warn when usable records span studies and select the
            most complete study; if True, raise SelectionError instead

    Returns:
        Dictionary mapping MammogramView to MammogramRecord (or None if not found)
    """

def get_preferred_views_with_order(
    records: list[MammogramRecord],
    preference_order: PreferenceOrder,
    strict: bool = False,
) -> dict[MammogramView, MammogramRecord | None]:
    """Select preferred views using a specific preference order.

    For each of the 4 standard views (L-MLO, R-MLO, L-CC, R-CC), selects the
    most preferred mammogram based on comparison logic using the specified
    preference order.

    Args:
        records: List of MammogramRecord objects to select from
        preference_order: The preference ordering strategy to use
        strict: If False, warn when usable records span studies and select the
            most complete study; if True, raise SelectionError instead

    Returns:
        Dictionary mapping MammogramView to MammogramRecord (or None if not found)
    """

def get_preferred_views_filtered(
    records: list[MammogramRecord],
    filter_config: FilterConfig,
    preference_order: PreferenceOrder,
    strict: bool = False,
) -> dict[MammogramView, MammogramRecord | None]:
    """Select preferred views with filtering.

    Applies filters before selecting preferred views. For each of the 4 standard
    views (L-MLO, R-MLO, L-CC, R-CC), selects the most preferred mammogram from
    filtered candidates.

    Args:
        records: List of MammogramRecord objects to select from
        filter_config: FilterConfig specifying which records to include
        preference_order: The preference ordering strategy to use
        strict: If False, warn when usable records span studies and select the
            most complete study; if True, raise SelectionError instead

    Returns:
        Dictionary mapping MammogramView to MammogramRecord (or None if not found)
    """

def plan_mammography_collection(
    path: str | Path,
    include_2d_views: bool = True,
    include_dbt: bool = True,
    preference_order: PreferenceOrder | None = None,
    strict: bool = False,
) -> dict[str, Any]:
    """Plan 2D mammography view and/or DBT inputs from a DICOM directory."""

def scan_dbt_study(input_dir: str | Path) -> dict[str, Any]:
    """Scan a study directory for old-format DBT series needing conversion."""

def convert_dbt_study(
    input_dir: str | Path,
    output_dir: str | Path,
    dry_run: bool = False,
    force: bool = False,
) -> dict[str, Any]:
    """Convert old-format DBT series and copy through other DICOM files."""
