/* auto-generated by NAPI-RS */
/* eslint-disable */
export type DicomInput = { path: string } | { bytes: Uint8Array; filename?: string }
export interface CandidateDiagnostic {
  inputIndex: number
  source: string
  status: string
  selectedAs: Array<string>
  filterReasons: Array<string>
  metadata: MammogramMetadata
}

export interface DicomInputInternal {
  path?: string
  bytes?: Uint8Array
  filename?: string
}

export declare function extractMetadata(input: DicomInput): MammogramMetadata

export interface InputError {
  inputIndex: number
  source: string | null
  code: string
  message: string
}

export interface MammogramMetadata {
  mammogramType: string
  dbtObjectKind: string
  laterality: string
  viewPosition: string
  viewModifiers: Array<string>
  imageType: string
  pixelSpacing: PixelSpacing | null
  isForProcessing: boolean
  hasImplant: boolean
  isSpotCompression: boolean
  isMagnified: boolean
  isImplantDisplaced: boolean
  manufacturer: string | null
  model: string | null
  numberOfFrames: number
  concatenationUid: string | null
  sopInstanceUidOfConcatenationSource: string | null
  isSecondaryCapture: boolean
  modality: string | null
  transferSyntaxUid: string | null
  transferSyntaxName: string | null
  compressionType: string | null
}

export interface MammogramRecord {
  source: string
  inputIndex: number | null
  metadata: MammogramMetadata
  studyInstanceUid: string | null
  seriesInstanceUid: string | null
  sopInstanceUid: string | null
  rows: number | null
  columns: number | null
  transferSyntaxUid: string | null
  isLossyCompressed: boolean
  isImplantDisplaced: boolean
  isSpotCompression: boolean
  isMagnified: boolean
}

export interface PixelSpacing {
  row: number
  column: number
}

export interface PreferredViewSelection {
  views: PreferredViewSlots
  missingViews: Array<string>
  warnings: Array<string>
  inputErrors: Array<InputError>
  candidates: Array<CandidateDiagnostic>
}

export interface PreferredViewSlots {
  rcc: MammogramRecord | null
  lcc: MammogramRecord | null
  rmlo: MammogramRecord | null
  lmlo: MammogramRecord | null
}

export interface SelectionOptions {
  preferenceOrder?: "default" | "synthetic-2d-first" | "tomo-first"
  strict?: boolean
}

export declare function selectPreferredViews(inputs: DicomInput[], options?: SelectionOptions): PreferredViewSelection

export declare function selectPreferredViewsFromDirectory(path: string, options?: SelectionOptions | undefined | null): PreferredViewSelection
